style(lint): disable magic value check in tests
canonical/starbase pull request #151
Opened 2023-11-09 20:02 UTC by lengau

fixes #148

- [ ] Have you followed the guidelines for contributing?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox`?

-----

2023-11-10 09:24 UTC, mr-cal approved these changes

2023-11-15 14:51 UTC, syu-w approved these changes

2023-11-16 12:12 UTC, sergiusens requested changes
typo

2023-11-16 12:12 UTC, sergiusens commented on pyproject.toml
> +    "PLR2004",  # Allow magic values is tests
```suggestion
    "PLR2004",  # Allow magic values in tests
```

2023-11-16 19:02 UTC, sergiusens approved these changes

2023-11-17 22:35 UTC, merged