style: replace yamllint with prettier
canonical/starbase pull request #305
Opened 2024-12-17 22:41 UTC by lengau

Lints and formats YAML, JSON, JSON5, Markdown and CSS files with prettier.

Cannot do TOML right now due to:
https://github.com/prettier/prettier/issues/15141

Fixes #273
CRAFT-3626

- [ ] Have you followed the guidelines for contributing?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox`?

-----

2024-12-17 22:55 UTC, medubelko commented
@lengau I'd need some extra time to test this against Markdown and CSS (if that's desired). Does this need merging ASAP?

2024-12-17 22:58 UTC, lengau commented
@medubelko not really, but all that happened here to the CSS file was it got auto-formatted. Prettier shouldn't make any changes that don't get parsed the same.

2024-12-18 08:15 UTC, upils requested changes
Should we also:
- remove yamllint from the `tox.ini` file?
- replace the call to yamllint in the precommit hook by a call to prettier?
- remove the `.yamllint.yaml` file?

2024-12-20 19:31 UTC, lengau commented on common.mk
> +PRETTIER_FILES=**.yaml **.yml **.json **.json5 **.css **.md
I did for unrelated reasons. There's no prettier plugin for it, but [docstrfmt](https://github.com/LilSpazJoekp/docstrfmt) looks promising. For the *particular* use case of our README though, it gives:

![image](https://github.com/user-attachments/assets/cc2b9cfb-286a-4103-aaca-0315222cfecb)

2024-12-20 19:42 UTC, lengau commented on common.mk
> +PRETTIER_FILES=**.yaml **.yml **.json **.json5 **.css **.md
I've raised this as a question for the new year: https://github.com/canonical/starbase/issues/308

2024-12-20 20:46 UTC, lengau commented on common.mk
> +else
More of a "don't care enough to check if node is on brew" case. Fixed!

2025-01-06 08:37 UTC, upils approved these changes

2025-01-06 13:37 UTC, mr-cal approved these changes

2025-01-06 17:34 UTC, medubelko commented on common.mk
> +PRETTIER_FILES=**.yaml **.yml **.json **.json5 **.css **.md
Regarding the README, it's possible that we'll be enforcing GFM formatting on them in the near future, so that particular concern is probably not worth stressing about.

2025-01-06 17:40 UTC, medubelko approved these changes

2025-01-07 20:42 UTC, merged